services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb-production
    restart: unless-stopped
    stdin_open: true
    network_mode: host
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./mongod.conf:/etc/mongod.conf
    command: 'mongod --config /etc/mongod.conf'

  cjsite:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    environment:
      NODE_ENV: production
    container_name: cj-production
    network_mode: host
    restart: unless-stopped
    depends_on:
      - mongodb_container

volumes:
  mongodata:
