version: "3.8"

services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb-production
    restart: unless-stopped
    stdin_open: true
    network_mode: host
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./mongod.conf:/etc/mongod.conf
    command: 'mongod --config /etc/mongod.conf'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/cjsite --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  cjsite:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    environment:
      NODE_ENV: production
    container_name: cj-production
    network_mode: host
    restart: unless-stopped

volumes:
  mongodata: